services:
  mcserver1:
    build: .
    volumes:
      - ./server:/docker/server
    ports:
      - '25565:25565'
    environment:
      - MC_VERSION=1.21.11
      #amount in GB minimum 1Gb
      - MC_RAM=8