services:
  survival:
    build: .
    volumes:
      - ./mcserver/survival:/docker/server
    ports:
      - '25565:25565'
      - '25575:25575'
    environment:
      - port=25565
      - rcon_port=25575
      - MC_VERSION=26.2
      #amount in GB minimum 1Gb
      - MC_RAM=4
      - PROJECT_ID=
      - MODRINTH_PROJECTS=Vebnzrzj,P1OZGk5p,GM9AuKjX,Lu3KuzdV
      
  creative:
    build: .
    volumes:
      - ./mcserver/creative:/docker/server
    ports:
      - '25566:25566'
      - '25576:25576'
    environment:
      - port=25566
      - rcon_port=25576
      - MC_VERSION=1.21.11
      #amount in GB minimum 1Gb
      - MC_RAM=4
      - PROJECT_ID=
      - MODRINTH_PROJECTS=Vebnzrzj,P1OZGk5p,GM9AuKjX,1u6JkXh5